name: GH Migration Analyzer CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: npm install eslint-config-prettier eslint-plugin-prettier && npx eslint .
    - name: Run tests
      run: yarn test